name: Matrix-Workflow
on: 
  push:  
  workflow_dispatch:

concurrency:
  cancel-in-progress : false
  group: branch-${{github.ref}}

jobs:
  matrix:
    concurrency:
      cancel-in-progress : false
      group: branch-${{github.ref}}-matrix
    
    name: matrix-job
    runs-on: ${{matrix.runner}}
    environment: testing-2
    strategy:
      matrix:
        runner: [ubuntu-20.04,ubuntu-18.04,windows-2022, windows-2019,macos-latest]
      max-parallel: 1
      fail-fast: true
    steps:
      - name: Running on ${{matrix.runner}}
        run: | 
          echo "hello from ${{matrix.runner}} "
          sleep 15
  
  job-2:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress : false
      group: branch-${{github.ref}}-job2
    steps:
      
      - name: Running on ${{matrix.runner}}
        run: | 
          echo "hello from ${{matrix.runner}} "
          sleep 15
  
